service:
  kakao:
    url: https://dapi.kakao.com/v2
    appkey: 4e75b900197e891107bcde200e7ce0ea
  naver:
    url: https://openapi.naver.com/v1
    client-id: eIzBU0pZMCumoU12SHBF
    client-secret: bClsLxfIeb